### PR TITLE
Ebook created

### LINKED ISSUE #7: Upstream issue: Create a pdf version
https://github.com/satwikkansal/wtfpython/issues/66

### PR DESCRIPTION
**Pull request by shreyateeza**
The README.md file along with some changes/modifications has been transformed into a pdf.
* Softwares Used
  1. [Sedja PDF Editor](https://www.sejda.com/)

Closes #7

NOTE:
- Please fill out the template below 

  - [x] Did you read the instructions in the [WORKFLOW](https://github.com/wtfpython-web/wtfpython-web/wiki/Workflow)?

  - [ ] Is your Python code styled according to the PEP8 code style convention as mentioned [here](https://www.python.org/dev/peps/pep-0008/)?

  - [ ] Have you run the tests?

  - [x] Have you followed commit guidelines as mentioned [here](https://github.com/wtfpython-web/wtfpython-web/wiki/Commit-Guidelines)?

### CODE REVIEW

**Comment by shreyateeza** [comment]
The hyperlinks in the Table of Contents section aren't functioning. It requires Adobe InDesign, PDF expert or other similar software which either requires to be purchased or not supported in Ubuntu.
And I use Ubuntu. :sweat_smile: 
@satwikkansal

**Comment by satwikkansal** [comment]
@shreyateeza did you try using pandoc (https://pandoc.org/MANUAL.html), afaik pandoc it converts markdown into hyperlinks and takes care of hyperlinks as well

**Comment by satwikkansal** [comment]
The concern is that hyperlinks are pretty convenient for the readers to navigate around, so we should try our best to have them, hope you understand :)

**Comment by shreyateeza** [comment]
Yes @satwikkansal! 
Pandoc was the first thing I tried but on running the command my pdf was not even running. The terminal used to get closed by itself.
I searched for a solution to the problem but couldn't find any proper one.

**Comment by realslimshanky** [comment]
@shreyateeza could you please elaborate on what problem you are facing with `pandoc`. Explain your setup and the process which you followed.
I would also recommend checking [Sphinx](http://www.sphinx-doc.org/en/stable/) out.

**Comment by shreyateeza** [comment]
Sphinx cannot be used for this. For pandoc, I am giving it a last try. If it doesn't work then I will tell here about the problem.

**Comment by shreyateeza** [comment]
@realslimshanky On using pandoc, I face these errors-

> shreyateeza@shreyateeza-Satellite-Pro-L510:~/Documents/wtfpython$ pandoc wtfpython.md -o wtfpython.pdf
> [pandoc warning] Could not find image `/images/tic-tac-toe/after_row_initialized.png', skipping...
> [pandoc warning] Could not find image `/images/tic-tac-toe/after_board_initialized.png', skipping...
> ! Package inputenc Error: Unicode char 🐍 (U+1F40D)
> (inputenc)                not set up for use with LaTeX.
> 
> See the inputenc package documentation for explanation.
> Type  H <return>  for immediate help.
>  ...                                              
>                                                   
> l.98 What the f*ck Python! 🐍
> 
> Try running pandoc with --latex-engine=xelatex.
> pandoc: Error producing PDF
> shreyateeza@shreyateeza-Satellite-Pro-L510:~/Documents/wtfpython$ pandoc wtfpython.md -o wtfpython.pdf
> ! Package inputenc Error: Unicode char 🐍 (U+1F40D)
> (inputenc)                not set up for use with LaTeX.
> 
> See the inputenc package documentation for explanation.
> Type  H <return>  for immediate help.
>  ...                                              
>                                                   
> l.107 What the f*ck Python! 🐍
> 
> Try running pandoc with --latex-engine=xelatex.
> pandoc: Error producing PDF
> shreyateeza@shreyateeza-Satellite-Pro-L510:~/Documents/wtfpython$ pandoc wtfpython.md -o wtfpython.pdf --latex-engine=xelatex
> pandoc: xelatex not found. xelatex is needed for pdf output.

There are two things-
1. This I suppose cannot be solved

> ! Package inputenc Error: Unicode char 🐍 (U+1F40D)
>     (inputenc)                not set up for use with LaTeX

2. Now for this, I am not getting how to install xelatex on ubuntu 18.04. I searched on google but didn't get any solution to this problem.

> xelatex not found

**Comment by shreyateeza** [comment]
> shreyateeza@shreyateeza-Satellite-Pro-L510:~/Documents/wtfpython$ pandoc wtfpython.md -o wtfpython.pdf> [pandoc warning] Could not find image `/images/tic-tac-toe/after_row_initialized.png', skipping...> [pandoc warning] Could not find image `/images/tic-tac-toe/after_board_initialized.png', skipping...> ! Package inputenc Error: Unicode char 🐍 (U+1F40D)> (inputenc)                not set up for use with LaTeX.> > See the inputenc package documentation for explanation.> Type  H <return>  for immediate help.>  ...                                              >                                                   > l.98 What the f*ck Python! 🐍> > Try running pandoc with --latex-engine=xelatex.> pandoc: Error producing PDF> shreyateeza@shreyateeza-Satellite-Pro-L510:~/Documents/wtfpython$ pandoc wtfpython.md -o wtfpython.pdf> ! Package inputenc Error: Unicode char 🐍 (U+1F40D)> (inputenc)                not set up for use with LaTeX.> > See the inputenc package documentation for explanation.> Type  H <return>  for immediate help.>  ...                                              >                                                   > l.107 What the f*ck Python! 🐍> > Try running pandoc with --latex-engine=xelatex.> pandoc: Error producing PDF> shreyateeza@shreyateeza-Satellite-Pro-L510:~/Documents/wtfpython$ pandoc wtfpython.md -o wtfpython.pdf --latex-engine=xelatex> pandoc: xelatex not found. xelatex is needed for pdf output.> shreyateeza@shreyateeza-Satellite-Pro-L510:~/Documents/wtfpython$ >

**Comment by shreyateeza** [comment]
On using pandoc, I am getting these errors:

1. This I suppose cannot be solved.
> ! Package inputenc Error: Unicode char 🐍 (U+1F40D)
> (inputenc)                not set up for use with LaTeX

2. For this problem, I didn't get a solution yet.

> shreyateeza@shreyateeza-Satellite-Pro-L510:~/Documents/wtfpython$ pandoc wtfpython.md -o wtfpython.pdf
> ! Package inputenc Error: Unicode char 🐍 (U+1F40D)
> (inputenc)                not set up for use with LaTeX.
> 
> See the inputenc package documentation for explanation.
> Type  H <return>  for immediate help.
>  ...                                              
>                                                   
> l.107 What the f*ck Python! 🐍
> 
> Try running pandoc with --latex-engine=xelatex.
> pandoc: Error producing PDF
> shreyateeza@shreyateeza-Satellite-Pro-L510:~/Documents/wtfpython$ pandoc wtfpython.md -o wtfpython.pdf --latex-engine=xelatex
> pandoc: xelatex not found. xelatex is needed for pdf output.
>

**Comment by shreyateeza** [comment]
Closed it by mistake. Reopening.

**Comment by realslimshanky** [comment]
@shreyateeza checkout this [thread](https://stackoverflow.com/questions/37208051/pandoc-xelatex-not-found-xelatex-is-needed-for-pdf-output) on Stackoverflow and try to link to correct binary.

**Comment by shreyateeza** [comment]
@realslimshanky This solution is for El Capitan (v10.11.4) and the package MacTex about which it has been mentioned in the answer requires macOS  10.10, 10.11, 10.12, or 10.13
Yosemite, El Capitan, Sierra, or High Sierra. It has nothing to do with Ubuntu.

**Comment by realslimshanky** [comment]
@shreyateeza the second solution deals with Linux based configuration. Check it out. https://stackoverflow.com/a/39010514/5128406

**Comment by shreyateeza** [comment]
@realslimshanky  Here is what I face on using the second solution-
make-error

Now I am  trying to find this problem's solution :joy:

**Comment by realslimshanky** [comment]
@shreyateeza please check if you are inside the correct directory. It looks like you are on the root `/` directory. Also, `make` will work only if you have a `Makefile` in the same location.

**Comment by realslimshanky** [comment]
@shreyateeza any updates?

**Comment by dufferzafar** [comment]
A direct run of `pandoc` won't work, because of those image not found errors. I think I commented out all the image links in the markdown itself.

As far as those Unicode errors are concerned, I don't think having `xelatex` would solve them either. I was seeing those errors too, but since I didn't really care about those characters, I just ignored them.

Let me know if you face any other errors. Will be happy to help.

**Comment by shreyateeza** [comment]
Closing this PR.

**Pull request closed without merging**
